### ISSUE TITLE
gradle编译通过 但是无法正常启动成功 提示报错 如图

### ISSUE THREAD

**Issue by sinbadxia** [FISCO-BCOS/bcos-node-proxy#18]
如题:
如图
![image](https://user-images.githubusercontent.com/22068559/128834806-19fd1da4-6067-471c-97f1-2c5b785a23e8.png)

![image](https://user-images.githubusercontent.com/22068559/128834495-824e2b29-f499-4d5d-a326-5ba164fdc4e8.png)

[root@FISCO-BCOS-DOCKER bcos-node-proxy]# ./gradlew build 

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
3 actionable tasks: 3 executed
==================================================================================

[root@FISCO-BCOS-DOCKER dist]# bash ./start.sh
try to start server org.fisco.bcos.proxy.Application
    server org.fisco.bcos.proxy.Application start successfully.
[root@FISCO-BCOS-DOCKER dist]# cd log
[root@FISCO-BCOS-DOCKER log]# ls -sl
total 20
 4 -rw-r--r-- 1 root root  1367 Aug 10 16:27 Bcos-node-proxy-error.log
12 -rw-r--r-- 1 root root 10110 Aug 10 16:27 Bcos-node-proxy.log
 4 -rw-r--r-- 1 root root   541 Aug 10 16:26 proxy.out
[root@FISCO-BCOS-DOCKER log]# cat Bcos-node-proxy-error.log
[ERROR][2021-08-10 16:27:02.337][main][wsweb][2224][2224][LOG_POINT]

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.http.HttpMessageConverters.configurePartConverters(HttpMessageConverters.java:140)

The following method did not exist:

    org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.getPartConverters()Ljava/util/List;

The method's class, org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter, is available from the following locations:

    jar:file:/home/dist/lib/spring-web-5.2.13.RELEASE.jar!/org/springframework/http/converter/support/AllEncompassingFormHttpMessageConverter.class

The class hierarchy was loaded from the following locations:

    org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter: file:/home/dist/lib/spring-web-5.2.13.RELEASE.jar
    org.springframework.http.converter.FormHttpMessageConverter: file:/home/dist/lib/spring-web-5.2.13.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter

以上 求助 谢谢

**Comment by lzb206** [comment]
你的问题解决了吗

**Comment by sinbadxia** [comment]
> 你的问题解决了吗

没有  一直编译不过  就没用这个代理了  直接用程序连4个节点

**Comment by cyjseagull** [comment]
需要更新spring-boot的版本，修复PR请参考[这里](https://github.com/FISCO-BCOS/bcos-node-proxy/pull/19)

**Comment by cyjseagull** [comment]
修复的PR已经合入，可以拉取main分支最新代码尝试，并通过如下命令验证是否ok:

```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"getClientVersion","params":[1],"id":1}' http://127.0.0.1:8170/bcos-node-proxy/rpc/v1
```

另外需要注意的是，此版本还没有升级到java-sdk最新版本，不支持 `>=14`版本的jdk

**Comment by sinbadxia** [comment]
> 修复的PR已经合入，可以拉取main分支最新代码尝试，并通过如下命令验证是否ok:
> 
> ```shell
> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"getClientVersion","params":[1],"id":1}' http://127.0.0.1:8170/bcos-node-proxy/rpc/v1
> ```
> 
> 另外需要注意的是，此版本还没有升级到java-sdk最新版本，不支持 `>=14`版本的jdk

好的 我试试  感谢！！！

**Comment by sinbadxia** [comment]
> > 修复的PR已经合入，可以拉取main分支最新代码尝试，并通过如下命令验证是否ok:
> > ```shell
> > curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"getClientVersion","params":[1],"id":1}' http://127.0.0.1:8170/bcos-node-proxy/rpc/v1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外需要注意的是，此版本还没有升级到java-sdk最新版本，不支持 `>=14`版本的jdk
> 
> 好的 我试试 感谢！！！

可以了   感谢 ！

![image](https://user-images.githubusercontent.com/22068559/129518031-df556663-6dae-486e-a5c1-02c0b7845757.png)
